version: '2'
services:
  nginx:
    image: hcouplet/jhipster-nginx-consul
    volumes:
    - './nginx/www:/var/www/:rw'
    - './nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:rw'
    ports:
    - "80"
